# ===================================
#  Relation Behavior Config
# ===================================

items:
    label: Line Item
    list: $/responsiv/pay/models/invoiceitem/columns.yaml
    form: $/responsiv/pay/models/invoiceitem/fields.yaml
    emptyMessage: Invoice has no line items
    view:
        toolbarButtons: create|delete

status_log:
    label: History
    emptyMessage: Invoice has no status history
    list: $/responsiv/pay/models/invoicestatuslog/columns.yaml
    form: $/responsiv/pay/models/invoicestatuslog/fields.yaml
    readOnly: true
    view:
        showSorting: false
        defaultSort: created_at

payment_log:
    label: Payments
    emptyMessage: Invoice has no payment attempts
    list: $/responsiv/pay/models/invoicelog/columns.yaml
    form: $/responsiv/pay/models/invoicelog/fields.yaml
    readOnly: true
    view:
        showSorting: false
        defaultSort: created_at
