# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: Tax Table

# Model Form Field configuration
form: $/responsiv/pay/models/tax/fields.yaml

# Model Class name
modelClass: Responsiv\Pay\Models\Tax

# Default redirect location
defaultRedirect: responsiv/pay/taxes

# Form Design
design:
    displayMode: basic
    size: 950

# Create page
create:
    title: Create Taxes
    redirect: responsiv/pay/taxes/update/:id
    redirectClose: responsiv/pay/taxes

# Update page
update:
    title: Edit Taxes
    redirect: responsiv/pay/taxes
    redirectClose: responsiv/pay/taxes

# Preview page
preview:
    title: Preview Taxes
